version: 2.1

jobs:
  lint:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: v2-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
