version: 2

jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: v2-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
